# Lora 实战

## Step1 导入相关包

In [2]:
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForSeq2Seq, TrainingArguments, Trainer

## Step2 加载数据集

In [3]:
import shutil
import os

# 源路径（input目录下的文件/文件夹）
source_path = "/kaggle/input/alpaca-data-zh/alpaca_data_zh/"

# 目标路径（working目录下，可自定义名称）
target_path = "/kaggle/working/alpaca_data_zh/"

# 若目标路径已存在，先删除（可选）
if os.path.exists(target_path):
    shutil.rmtree(target_path)  # 删除文件夹
    # 若复制单个文件，用 os.remove(target_path)

# 复制文件夹（包括所有子文件）
shutil.copytree(source_path, target_path)

# 若复制单个文件，用：
# shutil.copyfile(source_file, target_file)

# 验证是否复制成功
print("复制后的文件列表：", os.listdir(target_path))


ds = Dataset.load_from_disk("/kaggle/working/alpaca_data_zh/")
ds

复制后的文件列表： ['dataset_info.json', 'data-00000-of-00001.arrow', 'state.json']

Dataset({
    features: ['output', 'input', 'instruction'],
    num_rows: 26858
})

In [4]:
ds[:3]

{'output': ['以下是保持健康的三个提示：\n\n1. 保持身体活动。每天做适当的身体运动，如散步、跑步或游泳，能促进心血管健康，增强肌肉力量，并有助于减少体重。\n\n2. 均衡饮食。每天食用新鲜的蔬菜、水果、全谷物和脂肪含量低的蛋白质食物，避免高糖、高脂肪和加工食品，以保持健康的饮食习惯。\n\n3. 睡眠充足。睡眠对人体健康至关重要，成年人每天应保证 7-8 小时的睡眠。良好的睡眠有助于减轻压力，促进身体恢复，并提高注意力和记忆力。',
  '4/16等于1/4是因为我们可以约分分子分母都除以他们的最大公约数4，得到（4÷4）/ (16÷4）=1/4。分数的约分是用分子和分母除以相同的非零整数，来表示分数的一个相同的值，这因为分数实际上表示了分子除以分母，所以即使两个数同时除以同一个非零整数，分数的值也不会改变。所以4/16 和1/4是两种不同的书写形式，但它们的值相等。',
  '朱利叶斯·凯撒，又称尤利乌斯·恺撒（Julius Caesar）是古罗马的政治家、军事家和作家。他于公元前44年3月15日被刺杀。 \n\n根据历史记载，当时罗马元老院里一些参议员联合起来策划了对恺撒的刺杀行动，因为他们担心恺撒的统治将给罗马共和制带来威胁。在公元前44年3月15日（又称“3月的艾达之日”），恺撒去参加元老院会议时，被一群参议员包围并被攻击致死。据记载，他身中23刀，其中一刀最终致命。'],
 'input': ['', '输入：4/16', ''],
 'instruction': ['保持健康的三个提示。', '解释为什么以下分数等同于1/4', '朱利叶斯·凯撒是如何死亡的？']}

In [5]:
from huggingface_hub import snapshot_download

# 仓库地址（如 "Langboat/bloom-1b4-zh"）
repo_id = "Qwen/Qwen3-0.6B"
# 下载路径（自定义，如 "./bloom-1b4-zh"）
local_dir = "./Qwen/Qwen3-0.6B"

# 下载整个仓库
snapshot_download(
    repo_id=repo_id,
    local_dir=local_dir,
    # 可选：指定分支（默认 main）
    revision="main",
    # 可选：强制覆盖已有文件
    force_download=True
)

Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

LICENSE: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.50G [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

'/kaggle/working/Qwen/Qwen3-0.6B'

In [6]:
!pwd

/kaggle/working

## Step3 数据集预处理

In [7]:
tokenizer = AutoTokenizer.from_pretrained("./Qwen/Qwen3-0.6B")
tokenizer

Qwen2TokenizerFast(name_or_path='./Qwen/Qwen3-0.6B', vocab_size=151643, model_max_length=131072, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'eos_token': '<|im_end|>', 'pad_token': '<|endoftext|>', 'additional_special_tokens': ['<|im_start|>', '<|im_end|>', '<|object_ref_start|>', '<|object_ref_end|>', '<|box_start|>', '<|box_end|>', '<|quad_start|>', '<|quad_end|>', '<|vision_start|>', '<|vision_end|>', '<|vision_pad|>', '<|image_pad|>', '<|video_pad|>']}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	151643: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151644: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151645: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151646: AddedToken("<|object_ref_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151647: AddedToken("<|object_ref_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151648: AddedToken("<|box_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151649: AddedToken("<|box_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151650: AddedToken("<|quad_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151651: AddedToken("<|quad_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151652: AddedToken("<|vision_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151653: AddedToken("<|vision_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151654: AddedToken("<|vision_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151655: AddedToken("<|image_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151656: AddedToken("<|video_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151657: AddedToken("<tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151658: AddedToken("</tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151659: AddedToken("<|fim_prefix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151660: AddedToken("<|fim_middle|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151661: AddedToken("<|fim_suffix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151662: AddedToken("<|fim_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151663: AddedToken("<|repo_name|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151664: AddedToken("<|file_sep|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151665: AddedToken("<tool_response>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151666: AddedToken("</tool_response>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151667: AddedToken("<think>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
	151668: AddedToken("</think>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
}
)

In [8]:
def process_func(example):
    MAX_LENGTH = 256
    input_ids, attention_mask, labels = [], [], []
    instruction = tokenizer("\n".join(["Human: " + example["instruction"], example["input"]]).strip() + "\n\nAssistant: ")
    response = tokenizer(example["output"] + tokenizer.eos_token)
    input_ids = instruction["input_ids"] + response["input_ids"]
    attention_mask = instruction["attention_mask"] + response["attention_mask"]
    labels = [-100] * len(instruction["input_ids"]) + response["input_ids"]
    if len(input_ids) > MAX_LENGTH:
        input_ids = input_ids[:MAX_LENGTH]
        attention_mask = attention_mask[:MAX_LENGTH]
        labels = labels[:MAX_LENGTH]
    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels
    }

In [9]:
tokenized_ds = ds.map(process_func, remove_columns=ds.column_names)
tokenized_ds

Map:   0%|          | 0/26858 [00:00<?, ? examples/s]

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 26858
})

In [10]:
tokenizer.decode(tokenized_ds[1]["input_ids"])

'Human: 解释为什么以下分数等同于1/4\n输入：4/16\n\nAssistant: 4/16等于1/4是因为我们可以约分分子分母都除以他们的最大公约数4，得到（4÷4）/ (16÷4）=1/4。分数的约分是用分子和分母除以相同的非零整数，来表示分数的一个相同的值，这因为分数实际上表示了分子除以分母，所以即使两个数同时除以同一个非零整数，分数的值也不会改变。所以4/16 和1/4是两种不同的书写形式，但它们的值相等。<|im_end|>'

In [11]:
tokenizer.decode(list(filter(lambda x: x != -100, tokenized_ds[1]["labels"])))

'4/16等于1/4是因为我们可以约分分子分母都除以他们的最大公约数4，得到（4÷4）/ (16÷4）=1/4。分数的约分是用分子和分母除以相同的非零整数，来表示分数的一个相同的值，这因为分数实际上表示了分子除以分母，所以即使两个数同时除以同一个非零整数，分数的值也不会改变。所以4/16 和1/4是两种不同的书写形式，但它们的值相等。<|im_end|>'

## Step4 创建模型

In [10]:
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-0.6B")

/usr/local/lib/python3.11/dist-packages/pydantic/_internal/_generate_schema.py:2225: UnsupportedFieldAttributeWarning: The 'repr' attribute with value False was provided to the `Field()` function, which has no effect in the context it was used. 'repr' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/pydantic/_internal/_generate_schema.py:2225: UnsupportedFieldAttributeWarning: The 'frozen' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 'frozen' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(

In [13]:
for name, parameter in model.named_parameters():
    print(name)

model.embed_tokens.weight
model.layers.0.self_attn.q_proj.weight
model.layers.0.self_attn.k_proj.weight
model.layers.0.self_attn.v_proj.weight
model.layers.0.self_attn.o_proj.weight
model.layers.0.self_attn.q_norm.weight
model.layers.0.self_attn.k_norm.weight
model.layers.0.mlp.gate_proj.weight
model.layers.0.mlp.up_proj.weight
model.layers.0.mlp.down_proj.weight
model.layers.0.input_layernorm.weight
model.layers.0.post_attention_layernorm.weight
model.layers.1.self_attn.q_proj.weight
model.layers.1.self_attn.k_proj.weight
model.layers.1.self_attn.v_proj.weight
model.layers.1.self_attn.o_proj.weight
model.layers.1.self_attn.q_norm.weight
model.layers.1.self_attn.k_norm.weight
model.layers.1.mlp.gate_proj.weight
model.layers.1.mlp.up_proj.weight
model.layers.1.mlp.down_proj.weight
model.layers.1.input_layernorm.weight
model.layers.1.post_attention_layernorm.weight
model.layers.2.self_attn.q_proj.weight
model.layers.2.self_attn.k_proj.weight
model.layers.2.self_attn.v_proj.weight
model.layers.2.self_attn.o_proj.weight
model.layers.2.self_attn.q_norm.weight
model.layers.2.self_attn.k_norm.weight
model.layers.2.mlp.gate_proj.weight
model.layers.2.mlp.up_proj.weight
model.layers.2.mlp.down_proj.weight
model.layers.2.input_layernorm.weight
model.layers.2.post_attention_layernorm.weight
model.layers.3.self_attn.q_proj.weight
model.layers.3.self_attn.k_proj.weight
model.layers.3.self_attn.v_proj.weight
model.layers.3.self_attn.o_proj.weight
model.layers.3.self_attn.q_norm.weight
model.layers.3.self_attn.k_norm.weight
model.layers.3.mlp.gate_proj.weight
model.layers.3.mlp.up_proj.weight
model.layers.3.mlp.down_proj.weight
model.layers.3.input_layernorm.weight
model.layers.3.post_attention_layernorm.weight
model.layers.4.self_attn.q_proj.weight
model.layers.4.self_attn.k_proj.weight
model.layers.4.self_attn.v_proj.weight
model.layers.4.self_attn.o_proj.weight
model.layers.4.self_attn.q_norm.weight
model.layers.4.self_attn.k_norm.weight
model.layers.4.mlp.gate_proj.weight
model.layers.4.mlp.up_proj.weight
model.layers.4.mlp.down_proj.weight
model.layers.4.input_layernorm.weight
model.layers.4.post_attention_layernorm.weight
model.layers.5.self_attn.q_proj.weight
model.layers.5.self_attn.k_proj.weight
model.layers.5.self_attn.v_proj.weight
model.layers.5.self_attn.o_proj.weight
model.layers.5.self_attn.q_norm.weight
model.layers.5.self_attn.k_norm.weight
model.layers.5.mlp.gate_proj.weight
model.layers.5.mlp.up_proj.weight
model.layers.5.mlp.down_proj.weight
model.layers.5.input_layernorm.weight
model.layers.5.post_attention_layernorm.weight
model.layers.6.self_attn.q_proj.weight
model.layers.6.self_attn.k_proj.weight
model.layers.6.self_attn.v_proj.weight
model.layers.6.self_attn.o_proj.weight
model.layers.6.self_attn.q_norm.weight
model.layers.6.self_attn.k_norm.weight
model.layers.6.mlp.gate_proj.weight
model.layers.6.mlp.up_proj.weight
model.layers.6.mlp.down_proj.weight
model.layers.6.input_layernorm.weight
model.layers.6.post_attention_layernorm.weight
model.layers.7.self_attn.q_proj.weight
model.layers.7.self_attn.k_proj.weight
model.layers.7.self_attn.v_proj.weight
model.layers.7.self_attn.o_proj.weight
model.layers.7.self_attn.q_norm.weight
model.layers.7.self_attn.k_norm.weight
model.layers.7.mlp.gate_proj.weight
model.layers.7.mlp.up_proj.weight
model.layers.7.mlp.down_proj.weight
model.layers.7.input_layernorm.weight
model.layers.7.post_attention_layernorm.weight
model.layers.8.self_attn.q_proj.weight
model.layers.8.self_attn.k_proj.weight
model.layers.8.self_attn.v_proj.weight
model.layers.8.self_attn.o_proj.weight
model.layers.8.self_attn.q_norm.weight
model.layers.8.self_attn.k_norm.weight
model.layers.8.mlp.gate_proj.weight
model.layers.8.mlp.up_proj.weight
model.layers.8.mlp.down_proj.weight
model.layers.8.input_layernorm.weight
model.layers.8.post_attention_layernorm.weight
model.layers.9.self_attn.q_proj.weight
model.layers.9.self_attn.k_proj.weight
model.layers.9.self_attn.v_proj.weight
model.layers.9.self_attn.o_proj.weight
model.layers.9.self_attn.q_norm.weight
model.layers.9.self_attn.k_norm.weight
model.layers.9.mlp.gate_proj.weight
model.layers.9.mlp.up_proj.weight
model.layers.9.mlp.down_proj.weight
model.layers.9.input_layernorm.weight
model.layers.9.post_attention_layernorm.weight
model.layers.10.self_attn.q_proj.weight
model.layers.10.self_attn.k_proj.weight
model.layers.10.self_attn.v_proj.weight
model.layers.10.self_attn.o_proj.weight
model.layers.10.self_attn.q_norm.weight
model.layers.10.self_attn.k_norm.weight
model.layers.10.mlp.gate_proj.weight
model.layers.10.mlp.up_proj.weight
model.layers.10.mlp.down_proj.weight
model.layers.10.input_layernorm.weight
model.layers.10.post_attention_layernorm.weight
model.layers.11.self_attn.q_proj.weight
model.layers.11.self_attn.k_proj.weight
model.layers.11.self_attn.v_proj.weight
model.layers.11.self_attn.o_proj.weight
model.layers.11.self_attn.q_norm.weight
model.layers.11.self_attn.k_norm.weight
model.layers.11.mlp.gate_proj.weight
model.layers.11.mlp.up_proj.weight
model.layers.11.mlp.down_proj.weight
model.layers.11.input_layernorm.weight
model.layers.11.post_attention_layernorm.weight
model.layers.12.self_attn.q_proj.weight
model.layers.12.self_attn.k_proj.weight
model.layers.12.self_attn.v_proj.weight
model.layers.12.self_attn.o_proj.weight
model.layers.12.self_attn.q_norm.weight
model.layers.12.self_attn.k_norm.weight
model.layers.12.mlp.gate_proj.weight
model.layers.12.mlp.up_proj.weight
model.layers.12.mlp.down_proj.weight
model.layers.12.input_layernorm.weight
model.layers.12.post_attention_layernorm.weight
model.layers.13.self_attn.q_proj.weight
model.layers.13.self_attn.k_proj.weight
model.layers.13.self_attn.v_proj.weight
model.layers.13.self_attn.o_proj.weight
model.layers.13.self_attn.q_norm.weight
model.layers.13.self_attn.k_norm.weight
model.layers.13.mlp.gate_proj.weight
model.layers.13.mlp.up_proj.weight
model.layers.13.mlp.down_proj.weight
model.layers.13.input_layernorm.weight
model.layers.13.post_attention_layernorm.weight
model.layers.14.self_attn.q_proj.weight
model.layers.14.self_attn.k_proj.weight
model.layers.14.self_attn.v_proj.weight
model.layers.14.self_attn.o_proj.weight
model.layers.14.self_attn.q_norm.weight
model.layers.14.self_attn.k_norm.weight
model.layers.14.mlp.gate_proj.weight
model.layers.14.mlp.up_proj.weight
model.layers.14.mlp.down_proj.weight
model.layers.14.input_layernorm.weight
model.layers.14.post_attention_layernorm.weight
model.layers.15.self_attn.q_proj.weight
model.layers.15.self_attn.k_proj.weight
model.layers.15.self_attn.v_proj.weight
model.layers.15.self_attn.o_proj.weight
model.layers.15.self_attn.q_norm.weight
model.layers.15.self_attn.k_norm.weight
model.layers.15.mlp.gate_proj.weight
model.layers.15.mlp.up_proj.weight
model.layers.15.mlp.down_proj.weight
model.layers.15.input_layernorm.weight
model.layers.15.post_attention_layernorm.weight
model.layers.16.self_attn.q_proj.weight
model.layers.16.self_attn.k_proj.weight
model.layers.16.self_attn.v_proj.weight
model.layers.16.self_attn.o_proj.weight
model.layers.16.self_attn.q_norm.weight
model.layers.16.self_attn.k_norm.weight
model.layers.16.mlp.gate_proj.weight
model.layers.16.mlp.up_proj.weight
model.layers.16.mlp.down_proj.weight
model.layers.16.input_layernorm.weight
model.layers.16.post_attention_layernorm.weight
model.layers.17.self_attn.q_proj.weight
model.layers.17.self_attn.k_proj.weight
model.layers.17.self_attn.v_proj.weight
model.layers.17.self_attn.o_proj.weight
model.layers.17.self_attn.q_norm.weight
model.layers.17.self_attn.k_norm.weight
model.layers.17.mlp.gate_proj.weight
model.layers.17.mlp.up_proj.weight
model.layers.17.mlp.down_proj.weight
model.layers.17.input_layernorm.weight
model.layers.17.post_attention_layernorm.weight
model.layers.18.self_attn.q_proj.weight
model.layers.18.self_attn.k_proj.weight
model.layers.18.self_attn.v_proj.weight
model.layers.18.self_attn.o_proj.weight
model.layers.18.self_attn.q_norm.weight
model.layers.18.self_attn.k_norm.weight
model.layers.18.mlp.gate_proj.weight
model.layers.18.mlp.up_proj.weight
model.layers.18.mlp.down_proj.weight
model.layers.18.input_layernorm.weight
model.layers.18.post_attention_layernorm.weight
model.layers.19.self_attn.q_proj.weight
model.layers.19.self_attn.k_proj.weight
model.layers.19.self_attn.v_proj.weight
model.layers.19.self_attn.o_proj.weight
model.layers.19.self_attn.q_norm.weight
model.layers.19.self_attn.k_norm.weight
model.layers.19.mlp.gate_proj.weight
model.layers.19.mlp.up_proj.weight
model.layers.19.mlp.down_proj.weight
model.layers.19.input_layernorm.weight
model.layers.19.post_attention_layernorm.weight
model.layers.20.self_attn.q_proj.weight
model.layers.20.self_attn.k_proj.weight
model.layers.20.self_attn.v_proj.weight
model.layers.20.self_attn.o_proj.weight
model.layers.20.self_attn.q_norm.weight
model.layers.20.self_attn.k_norm.weight
model.layers.20.mlp.gate_proj.weight
model.layers.20.mlp.up_proj.weight
model.layers.20.mlp.down_proj.weight
model.layers.20.input_layernorm.weight
model.layers.20.post_attention_layernorm.weight
model.layers.21.self_attn.q_proj.weight
model.layers.21.self_attn.k_proj.weight
model.layers.21.self_attn.v_proj.weight
model.layers.21.self_attn.o_proj.weight
model.layers.21.self_attn.q_norm.weight
model.layers.21.self_attn.k_norm.weight
model.layers.21.mlp.gate_proj.weight
model.layers.21.mlp.up_proj.weight
model.layers.21.mlp.down_proj.weight
model.layers.21.input_layernorm.weight
model.layers.21.post_attention_layernorm.weight
model.layers.22.self_attn.q_proj.weight
model.layers.22.self_attn.k_proj.weight
model.layers.22.self_attn.v_proj.weight
model.layers.22.self_attn.o_proj.weight
model.layers.22.self_attn.q_norm.weight
model.layers.22.self_attn.k_norm.weight
model.layers.22.mlp.gate_proj.weight
model.layers.22.mlp.up_proj.weight
model.layers.22.mlp.down_proj.weight
model.layers.22.input_layernorm.weight
model.layers.22.post_attention_layernorm.weight
model.layers.23.self_attn.q_proj.weight
model.layers.23.self_attn.k_proj.weight
model.layers.23.self_attn.v_proj.weight
model.layers.23.self_attn.o_proj.weight
model.layers.23.self_attn.q_norm.weight
model.layers.23.self_attn.k_norm.weight
model.layers.23.mlp.gate_proj.weight
model.layers.23.mlp.up_proj.weight
model.layers.23.mlp.down_proj.weight
model.layers.23.input_layernorm.weight
model.layers.23.post_attention_layernorm.weight
model.layers.24.self_attn.q_proj.weight
model.layers.24.self_attn.k_proj.weight
model.layers.24.self_attn.v_proj.weight
model.layers.24.self_attn.o_proj.weight
model.layers.24.self_attn.q_norm.weight
model.layers.24.self_attn.k_norm.weight
model.layers.24.mlp.gate_proj.weight
model.layers.24.mlp.up_proj.weight
model.layers.24.mlp.down_proj.weight
model.layers.24.input_layernorm.weight
model.layers.24.post_attention_layernorm.weight
model.layers.25.self_attn.q_proj.weight
model.layers.25.self_attn.k_proj.weight
model.layers.25.self_attn.v_proj.weight
model.layers.25.self_attn.o_proj.weight
model.layers.25.self_attn.q_norm.weight
model.layers.25.self_attn.k_norm.weight
model.layers.25.mlp.gate_proj.weight
model.layers.25.mlp.up_proj.weight
model.layers.25.mlp.down_proj.weight
model.layers.25.input_layernorm.weight
model.layers.25.post_attention_layernorm.weight
model.layers.26.self_attn.q_proj.weight
model.layers.26.self_attn.k_proj.weight
model.layers.26.self_attn.v_proj.weight
model.layers.26.self_attn.o_proj.weight
model.layers.26.self_attn.q_norm.weight
model.layers.26.self_attn.k_norm.weight
model.layers.26.mlp.gate_proj.weight
model.layers.26.mlp.up_proj.weight
model.layers.26.mlp.down_proj.weight
model.layers.26.input_layernorm.weight
model.layers.26.post_attention_layernorm.weight
model.layers.27.self_attn.q_proj.weight
model.layers.27.self_attn.k_proj.weight
model.layers.27.self_attn.v_proj.weight
model.layers.27.self_attn.o_proj.weight
model.layers.27.self_attn.q_norm.weight
model.layers.27.self_attn.k_norm.weight
model.layers.27.mlp.gate_proj.weight
model.layers.27.mlp.up_proj.weight
model.layers.27.mlp.down_proj.weight
model.layers.27.input_layernorm.weight
model.layers.27.post_attention_layernorm.weight
model.norm.weight

## Lora

### PEFT Step1 配置文件

In [12]:
from peft import LoraConfig, TaskType, get_peft_model

config = LoraConfig(task_type=TaskType.CAUSAL_LM, modules_to_save=["word_embeddings"])
config

LoraConfig(task_type=<TaskType.CAUSAL_LM: 'CAUSAL_LM'>, peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path=None, revision=None, inference_mode=False, r=8, target_modules=None, exclude_modules=None, lora_alpha=8, lora_dropout=0.0, fan_in_fan_out=False, bias='none', use_rslora=False, modules_to_save=['word_embeddings'], init_lora_weights=True, layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={}, megatron_config=None, megatron_core='megatron.core', trainable_token_indices=None, loftq_config={}, eva_config=None, corda_config=None, use_dora=False, use_qalora=False, qalora_group_size=16, layer_replication=None, runtime_config=LoraRuntimeConfig(ephemeral_gpu_offload=False), lora_bias=False)

### PEFT Step2 创建模型

In [15]:
model = get_peft_model(model, config)

In [16]:
config

LoraConfig(task_type=<TaskType.CAUSAL_LM: 'CAUSAL_LM'>, peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path='Qwen/Qwen3-0.6B', revision=None, inference_mode=False, r=8, target_modules={'q_proj', 'v_proj'}, exclude_modules=None, lora_alpha=8, lora_dropout=0.0, fan_in_fan_out=False, bias='none', use_rslora=False, modules_to_save=['word_embeddings'], init_lora_weights=True, layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={}, megatron_config=None, megatron_core='megatron.core', trainable_token_indices=None, loftq_config={}, eva_config=None, corda_config=None, use_dora=False, use_qalora=False, qalora_group_size=16, layer_replication=None, runtime_config=LoraRuntimeConfig(ephemeral_gpu_offload=False), lora_bias=False)

In [17]:
for name, parameter in model.named_parameters():
    print(name)

base_model.model.model.embed_tokens.weight
base_model.model.model.layers.0.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.0.self_attn.k_proj.weight
base_model.model.model.layers.0.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.0.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.0.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.0.self_attn.o_proj.weight
base_model.model.model.layers.0.self_attn.q_norm.weight
base_model.model.model.layers.0.self_attn.k_norm.weight
base_model.model.model.layers.0.mlp.gate_proj.weight
base_model.model.model.layers.0.mlp.up_proj.weight
base_model.model.model.layers.0.mlp.down_proj.weight
base_model.model.model.layers.0.input_layernorm.weight
base_model.model.model.layers.0.post_attention_layernorm.weight
base_model.model.model.layers.1.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.1.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.1.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.1.self_attn.k_proj.weight
base_model.model.model.layers.1.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.1.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.1.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.1.self_attn.o_proj.weight
base_model.model.model.layers.1.self_attn.q_norm.weight
base_model.model.model.layers.1.self_attn.k_norm.weight
base_model.model.model.layers.1.mlp.gate_proj.weight
base_model.model.model.layers.1.mlp.up_proj.weight
base_model.model.model.layers.1.mlp.down_proj.weight
base_model.model.model.layers.1.input_layernorm.weight
base_model.model.model.layers.1.post_attention_layernorm.weight
base_model.model.model.layers.2.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.2.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.2.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.2.self_attn.k_proj.weight
base_model.model.model.layers.2.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.2.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.2.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.2.self_attn.o_proj.weight
base_model.model.model.layers.2.self_attn.q_norm.weight
base_model.model.model.layers.2.self_attn.k_norm.weight
base_model.model.model.layers.2.mlp.gate_proj.weight
base_model.model.model.layers.2.mlp.up_proj.weight
base_model.model.model.layers.2.mlp.down_proj.weight
base_model.model.model.layers.2.input_layernorm.weight
base_model.model.model.layers.2.post_attention_layernorm.weight
base_model.model.model.layers.3.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.3.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.3.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.3.self_attn.k_proj.weight
base_model.model.model.layers.3.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.3.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.3.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.3.self_attn.o_proj.weight
base_model.model.model.layers.3.self_attn.q_norm.weight
base_model.model.model.layers.3.self_attn.k_norm.weight
base_model.model.model.layers.3.mlp.gate_proj.weight
base_model.model.model.layers.3.mlp.up_proj.weight
base_model.model.model.layers.3.mlp.down_proj.weight
base_model.model.model.layers.3.input_layernorm.weight
base_model.model.model.layers.3.post_attention_layernorm.weight
base_model.model.model.layers.4.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.4.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.4.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.4.self_attn.k_proj.weight
base_model.model.model.layers.4.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.4.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.4.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.4.self_attn.o_proj.weight
base_model.model.model.layers.4.self_attn.q_norm.weight
base_model.model.model.layers.4.self_attn.k_norm.weight
base_model.model.model.layers.4.mlp.gate_proj.weight
base_model.model.model.layers.4.mlp.up_proj.weight
base_model.model.model.layers.4.mlp.down_proj.weight
base_model.model.model.layers.4.input_layernorm.weight
base_model.model.model.layers.4.post_attention_layernorm.weight
base_model.model.model.layers.5.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.5.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.5.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.5.self_attn.k_proj.weight
base_model.model.model.layers.5.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.5.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.5.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.5.self_attn.o_proj.weight
base_model.model.model.layers.5.self_attn.q_norm.weight
base_model.model.model.layers.5.self_attn.k_norm.weight
base_model.model.model.layers.5.mlp.gate_proj.weight
base_model.model.model.layers.5.mlp.up_proj.weight
base_model.model.model.layers.5.mlp.down_proj.weight
base_model.model.model.layers.5.input_layernorm.weight
base_model.model.model.layers.5.post_attention_layernorm.weight
base_model.model.model.layers.6.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.6.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.6.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.6.self_attn.k_proj.weight
base_model.model.model.layers.6.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.6.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.6.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.6.self_attn.o_proj.weight
base_model.model.model.layers.6.self_attn.q_norm.weight
base_model.model.model.layers.6.self_attn.k_norm.weight
base_model.model.model.layers.6.mlp.gate_proj.weight
base_model.model.model.layers.6.mlp.up_proj.weight
base_model.model.model.layers.6.mlp.down_proj.weight
base_model.model.model.layers.6.input_layernorm.weight
base_model.model.model.layers.6.post_attention_layernorm.weight
base_model.model.model.layers.7.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.7.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.7.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.7.self_attn.k_proj.weight
base_model.model.model.layers.7.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.7.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.7.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.7.self_attn.o_proj.weight
base_model.model.model.layers.7.self_attn.q_norm.weight
base_model.model.model.layers.7.self_attn.k_norm.weight
base_model.model.model.layers.7.mlp.gate_proj.weight
base_model.model.model.layers.7.mlp.up_proj.weight
base_model.model.model.layers.7.mlp.down_proj.weight
base_model.model.model.layers.7.input_layernorm.weight
base_model.model.model.layers.7.post_attention_layernorm.weight
base_model.model.model.layers.8.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.8.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.8.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.8.self_attn.k_proj.weight
base_model.model.model.layers.8.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.8.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.8.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.8.self_attn.o_proj.weight
base_model.model.model.layers.8.self_attn.q_norm.weight
base_model.model.model.layers.8.self_attn.k_norm.weight
base_model.model.model.layers.8.mlp.gate_proj.weight
base_model.model.model.layers.8.mlp.up_proj.weight
base_model.model.model.layers.8.mlp.down_proj.weight
base_model.model.model.layers.8.input_layernorm.weight
base_model.model.model.layers.8.post_attention_layernorm.weight
base_model.model.model.layers.9.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.9.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.9.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.9.self_attn.k_proj.weight
base_model.model.model.layers.9.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.9.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.9.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.9.self_attn.o_proj.weight
base_model.model.model.layers.9.self_attn.q_norm.weight
base_model.model.model.layers.9.self_attn.k_norm.weight
base_model.model.model.layers.9.mlp.gate_proj.weight
base_model.model.model.layers.9.mlp.up_proj.weight
base_model.model.model.layers.9.mlp.down_proj.weight
base_model.model.model.layers.9.input_layernorm.weight
base_model.model.model.layers.9.post_attention_layernorm.weight
base_model.model.model.layers.10.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.10.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.10.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.10.self_attn.k_proj.weight
base_model.model.model.layers.10.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.10.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.10.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.10.self_attn.o_proj.weight
base_model.model.model.layers.10.self_attn.q_norm.weight
base_model.model.model.layers.10.self_attn.k_norm.weight
base_model.model.model.layers.10.mlp.gate_proj.weight
base_model.model.model.layers.10.mlp.up_proj.weight
base_model.model.model.layers.10.mlp.down_proj.weight
base_model.model.model.layers.10.input_layernorm.weight
base_model.model.model.layers.10.post_attention_layernorm.weight
base_model.model.model.layers.11.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.11.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.11.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.11.self_attn.k_proj.weight
base_model.model.model.layers.11.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.11.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.11.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.11.self_attn.o_proj.weight
base_model.model.model.layers.11.self_attn.q_norm.weight
base_model.model.model.layers.11.self_attn.k_norm.weight
base_model.model.model.layers.11.mlp.gate_proj.weight
base_model.model.model.layers.11.mlp.up_proj.weight
base_model.model.model.layers.11.mlp.down_proj.weight
base_model.model.model.layers.11.input_layernorm.weight
base_model.model.model.layers.11.post_attention_layernorm.weight
base_model.model.model.layers.12.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.12.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.12.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.12.self_attn.k_proj.weight
base_model.model.model.layers.12.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.12.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.12.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.12.self_attn.o_proj.weight
base_model.model.model.layers.12.self_attn.q_norm.weight
base_model.model.model.layers.12.self_attn.k_norm.weight
base_model.model.model.layers.12.mlp.gate_proj.weight
base_model.model.model.layers.12.mlp.up_proj.weight
base_model.model.model.layers.12.mlp.down_proj.weight
base_model.model.model.layers.12.input_layernorm.weight
base_model.model.model.layers.12.post_attention_layernorm.weight
base_model.model.model.layers.13.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.13.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.13.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.13.self_attn.k_proj.weight
base_model.model.model.layers.13.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.13.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.13.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.13.self_attn.o_proj.weight
base_model.model.model.layers.13.self_attn.q_norm.weight
base_model.model.model.layers.13.self_attn.k_norm.weight
base_model.model.model.layers.13.mlp.gate_proj.weight
base_model.model.model.layers.13.mlp.up_proj.weight
base_model.model.model.layers.13.mlp.down_proj.weight
base_model.model.model.layers.13.input_layernorm.weight
base_model.model.model.layers.13.post_attention_layernorm.weight
base_model.model.model.layers.14.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.14.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.14.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.14.self_attn.k_proj.weight
base_model.model.model.layers.14.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.14.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.14.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.14.self_attn.o_proj.weight
base_model.model.model.layers.14.self_attn.q_norm.weight
base_model.model.model.layers.14.self_attn.k_norm.weight
base_model.model.model.layers.14.mlp.gate_proj.weight
base_model.model.model.layers.14.mlp.up_proj.weight
base_model.model.model.layers.14.mlp.down_proj.weight
base_model.model.model.layers.14.input_layernorm.weight
base_model.model.model.layers.14.post_attention_layernorm.weight
base_model.model.model.layers.15.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.15.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.15.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.15.self_attn.k_proj.weight
base_model.model.model.layers.15.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.15.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.15.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.15.self_attn.o_proj.weight
base_model.model.model.layers.15.self_attn.q_norm.weight
base_model.model.model.layers.15.self_attn.k_norm.weight
base_model.model.model.layers.15.mlp.gate_proj.weight
base_model.model.model.layers.15.mlp.up_proj.weight
base_model.model.model.layers.15.mlp.down_proj.weight
base_model.model.model.layers.15.input_layernorm.weight
base_model.model.model.layers.15.post_attention_layernorm.weight
base_model.model.model.layers.16.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.16.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.16.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.16.self_attn.k_proj.weight
base_model.model.model.layers.16.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.16.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.16.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.16.self_attn.o_proj.weight
base_model.model.model.layers.16.self_attn.q_norm.weight
base_model.model.model.layers.16.self_attn.k_norm.weight
base_model.model.model.layers.16.mlp.gate_proj.weight
base_model.model.model.layers.16.mlp.up_proj.weight
base_model.model.model.layers.16.mlp.down_proj.weight
base_model.model.model.layers.16.input_layernorm.weight
base_model.model.model.layers.16.post_attention_layernorm.weight
base_model.model.model.layers.17.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.17.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.17.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.17.self_attn.k_proj.weight
base_model.model.model.layers.17.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.17.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.17.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.17.self_attn.o_proj.weight
base_model.model.model.layers.17.self_attn.q_norm.weight
base_model.model.model.layers.17.self_attn.k_norm.weight
base_model.model.model.layers.17.mlp.gate_proj.weight
base_model.model.model.layers.17.mlp.up_proj.weight
base_model.model.model.layers.17.mlp.down_proj.weight
base_model.model.model.layers.17.input_layernorm.weight
base_model.model.model.layers.17.post_attention_layernorm.weight
base_model.model.model.layers.18.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.18.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.18.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.18.self_attn.k_proj.weight
base_model.model.model.layers.18.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.18.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.18.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.18.self_attn.o_proj.weight
base_model.model.model.layers.18.self_attn.q_norm.weight
base_model.model.model.layers.18.self_attn.k_norm.weight
base_model.model.model.layers.18.mlp.gate_proj.weight
base_model.model.model.layers.18.mlp.up_proj.weight
base_model.model.model.layers.18.mlp.down_proj.weight
base_model.model.model.layers.18.input_layernorm.weight
base_model.model.model.layers.18.post_attention_layernorm.weight
base_model.model.model.layers.19.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.19.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.19.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.19.self_attn.k_proj.weight
base_model.model.model.layers.19.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.19.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.19.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.19.self_attn.o_proj.weight
base_model.model.model.layers.19.self_attn.q_norm.weight
base_model.model.model.layers.19.self_attn.k_norm.weight
base_model.model.model.layers.19.mlp.gate_proj.weight
base_model.model.model.layers.19.mlp.up_proj.weight
base_model.model.model.layers.19.mlp.down_proj.weight
base_model.model.model.layers.19.input_layernorm.weight
base_model.model.model.layers.19.post_attention_layernorm.weight
base_model.model.model.layers.20.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.20.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.20.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.20.self_attn.k_proj.weight
base_model.model.model.layers.20.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.20.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.20.self_attn.v_proj.lora_B.default.weight
base_model.model.model.layers.20.self_attn.o_proj.weight
base_model.model.model.layers.20.self_attn.q_norm.weight
base_model.model.model.layers.20.self_attn.k_norm.weight
base_model.model.model.layers.20.mlp.gate_proj.weight
base_model.model.model.layers.20.mlp.up_proj.weight
base_model.model.model.layers.20.mlp.down_proj.weight
base_model.model.model.layers.20.input_layernorm.weight
base_model.model.model.layers.20.post_attention_layernorm.weight
base_model.model.model.layers.21.self_attn.q_proj.base_layer.weight
base_model.model.model.layers.21.self_attn.q_proj.lora_A.default.weight
base_model.model.model.layers.21.self_attn.q_proj.lora_B.default.weight
base_model.model.model.layers.21.self_attn.k_proj.weight
base_model.model.model.layers.21.self_attn.v_proj.base_layer.weight
base_model.model.model.layers.21.self_attn.v_proj.lora_A.default.weight
base_model.model.model.layers.21.self_attn.v_proj.lora_B.default.weight

In [18]:
model.print_trainable_parameters()

trainable params: 1,146,880 || all params: 597,196,800 || trainable%: 0.1920

## Step5 配置训练参数

In [19]:
args = TrainingArguments(
    output_dir="./chatbot",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=8,
    logging_steps=10,
    num_train_epochs=1,
    report_to="none"
)

## Step6 创建训练器

In [20]:
trainer = Trainer(
    model=model,
    args=args,
    tokenizer=tokenizer,
    train_dataset=tokenized_ds,
    data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True),
)

/tmp/ipykernel_38/1988846643.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

## Step7 模型训练

In [21]:
trainer.train()

TrainOutput(global_step=1679, training_loss=1.949883185517866, metrics={'train_runtime': 2115.3691, 'train_samples_per_second': 12.697, 'train_steps_per_second': 0.794, 'total_flos': 7152758508355584.0, 'train_loss': 1.949883185517866, 'epoch': 1.0})

## Step8 模型推理

In [22]:
model = model.cuda()
ipt = tokenizer("Human: {}\n{}".format("考试有哪些技巧？", "").strip() + "\n\nAssistant: ", return_tensors="pt").to(model.device)
tokenizer.decode(model.generate(**ipt, max_length=128, do_sample=True)[0], skip_special_tokens=True)

'Human: 考试有哪些技巧？\n\nAssistant: 考试技巧有很多，以下是一些常见的技巧，可以帮助你更好地准备和应对考试：\n\n1. 制定计划：根据你所学的知识和考试内容，制定一个详细的学习计划，包括每天的学习时间、复习计划和目标。\n\n2. 做好复习：复习是考试成功的必要条件，你可以利用笔记、练习题和错题本来复习你的知识。同时，可以使用一些复习方法，如背诵、口述、记忆和归纳等。\n\n3. 多做题：通过大量练习，你可以提高解题能力'

In [23]:
model = model.cuda()
ipt = tokenizer("Human: {}\n{}".format("你叫什么名字？", "").strip() + "\n\nAssistant: ", return_tensors="pt").to(model.device)
tokenizer.decode(model.generate(**ipt, max_length=128, do_sample=True)[0], skip_special_tokens=True)

'Human: 你叫什么名字？\n\nAssistant: 我叫我叫"我"，是一个虚拟助手，可以为您提供各种帮助和支持。'

In [24]:
model = model.cuda()
ipt = tokenizer("Human: {}\n{}".format("你知道江西科技学院吗？", "").strip() + "\n\nAssistant: ", return_tensors="pt").to(model.device)
tokenizer.decode(model.generate(**ipt, max_length=128, do_sample=True)[0], skip_special_tokens=True)

'Human: 你知道江西科技学院吗？\n\nAssistant: 江西科技学院位于江西省南昌市，是一所综合性本科院校。它是由江西省人民政府发起设立的，成立于2005年，拥有江西省科技厅主管的职能。学院的学科门类广泛，涵盖计算机、数学、物理、化学、生物、医学、教育学等多门，设有多个国家级和省级重点实验室，拥有丰富的科研成果和良好的教学资源。江西科技学院注重实践教学，重视学生创新能力的培养，致力于为社会培养高素质、高技能的科技人才。'

## Step9 拓展尝试

### 9.1 增加 epoch

In [16]:
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-0.6B")
model = get_peft_model(model, config)

In [17]:
args = TrainingArguments(
    output_dir="./chatbot",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=8,
    logging_steps=10,
    num_train_epochs=3,
    report_to="none"
)

In [18]:
trainer = Trainer(
    model=model,
    args=args,
    tokenizer=tokenizer,
    train_dataset=tokenized_ds,
    data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True),
)

/tmp/ipykernel_38/1988846643.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [ ]:
trainer.train()